  FROM node:14.10-alpine AS builder

  RUN mkdir -p /home/node/build/node_modules && chown -R node:node /home/node/build
  WORKDIR /home/node/build
  COPY --chown=node:node package.json ./
  USER node
  COPY --chown=node:node . .
  RUN npm install
  RUN npm run build

  FROM node:14.10-alpine
  
  RUN mkdir -p /home/node/web/node_modules && chown -R node:node /home/node/web

  WORKDIR /home/node/web
  
  RUN npm install pm2 -g

  USER node

  COPY --chown=node:node --from=builder /home/node/build/node_modules ./node_modules
  COPY --chown=node:node --from=builder /home/node/build/server ./server
  COPY --chown=node:node --from=builder /home/node/build/.env .
  COPY --chown=node:node --from=builder /home/node/build/build ./build
  COPY --chown=node:node --from=builder /home/node/build/process.yml .


  CMD ["pm2-runtime", "process.yml"]